Add missing dependencies
Fixed these errors: 

Error: Cannot find module 'socket.io/node_modules/cookie'
Error: Cannot find module 'socket.io/node_modules/connect'
Error: Cannot find module 'socket.io/node_modules/redis'